spring.application.name=product
server.port=8081

spring.datasource.url=jdbc:mysql://localhost/ex_ms_order
spring.datasource.username=root
spring.datasource.password=yamine

spring.jpa.hibernate.ddl-auto=update